# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0d983d5f1193b3fa7203360eb7014d4f68b8ba74facf66476d3afb94b8a85ef9bb1a3da5bdc8a3cf2a505c9ae573b40c80e0d25a85384f1067e2a3079cc14ce

test:
  secret_key_base: 5ddbb580009763a39d23270862a7a3ca42210a97c3c59a19339495b952ea4ffcaf264574a210eb3c6217d4aa730576af66343c1fbca24d4725109664dd7bc63e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
